### ISSUE TITLE
Add a new feature?

### ISSUE THREAD

**Issue by starmc63** [ens-gijs/minecraft-stronghold-locator#3]
Hello, I'm sorry to bother you. I really like your tool https://github.com/ens-gijs/NBT, but I didn't see the issue section on its page. Maybe you can create a Powerful Utilities for the bukkit server to parse the. mca region file and convert the data into a bukkit.Block object based on specific coordinates,(int int) ,or is there any way to convert the. mca file into a bukkit.Chunk object?Also, convert the entities. mca file to bukkit.Entity Object or other BukkitAPI forms.

**Comment by starmc63** [comment]
Server Version Paper 1.21.1

**Comment by starmc63** [comment]
Mainly beacause I want to use https://github.com/ens-gijs/NBT in my Bukkit plugin development. which can read the .mca file in the form of plugin.

**Comment by ens-gijs** [comment]
It should be possible, but not something I need and not something I'm likely to do. It definitely is not something that belongs in this library - but something could be built using this library to interact with paper.

If I wanted to do this myself with the least amount of effort, I would create a world that I don't let payers in, use the `RegionFileRelocator` to place .mca files into it, then use the normal bukkit api to load and interact with chunks and entities.

**Comment by ens-gijs** [comment]
Here's a sample using `RegionFileRelocator ` pulled from one of my plugins using this library

```java
try (RegionFileRelocator relocator = new RegionFileRelocator()
        .sourceRoot(tmpPath.toAbsolutePath().toString())
        .destinationRoot(duelWorld.getWorldDimensionFolder())
) {
    for (int i = 0; i < remappedRegionXZ.size(); i++) {
        IntPoint2D oxz = zoneConfig.getRegionFileCoords().get(i);
        IntPoint2D nxz = remappedRegionXZ.get(i);
        logger.info("Relocating archived %s to %s %s", oxz, duelWorld.worldName(), nxz);
        boolean ok = relocator.relocate(oxz.getX(), oxz.getZ(), nxz.getX(), nxz.getZ());
        if (!ok) {
            logger.warning("Relocation of region %s to %s didn't do anything!", oxz, nxz);
        }
    }
}
```

The dimension folder is calculated with
```java
public static Path worldDimensionPath(@NotNull String worldName, @Nullable World.Environment environment) {
    if (environment != null) {
        return Path.of(Bukkit.getServer().getWorldContainer().getAbsolutePath(), worldName,
                switch (environment) {
                    case NETHER -> "/DIM-1";
                    case THE_END -> "/DIM1";
                    case CUSTOM -> "/DIM-999";
                    default -> "";
                });
    } else {
        return Path.of(Bukkit.getServer().getWorldContainer().getAbsolutePath(), worldName);
    }
}
```

**Comment by ens-gijs** [comment]
> Mainly beacause I want to use https://github.com/ens-gijs/NBT in my Bukkit plugin development. which can read the .mca file in the form of plugin.

If you're mostly interested in better unit testing - look at MockBukkit. I've started to use it and contribute there too. I'll think on it for a while and if I can see a reasonably simple way to leverage this NBT fork to inject seemingly real, whole, chunks into unit tests - I just might do it ;)
